### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by kspcr** [arunKumarNOP/Saavn-Downloader-Android#3]
Unfortunately "app" has stopped working. This app is crasing every time , when downloading a song.

**Comment by arunKumarNOP** [comment]
Please post the log from the logcat when the app crashes, at my side its working fine so without logs i cannot fix it.

**Comment by sudiptomahato** [comment]
App is crashing every time you click download. below is the log.
I am using Xiaomi MI 5, Android 6.0.1, MIUI 8.1


java.lang.IllegalArgumentException: Version must be >= 1, was -1
	at android.database.sqlite.SQLiteOpenHelper.<init>(SQLiteOpenHelper.java:99)
	at android.database.sqlite.SQLiteOpenHelper.<init>(SQLiteOpenHelper.java:77)
	at com.arunkr.saavn.downloader.DatabaseHelper.<init>(DatabaseHelper.java:30)
	at com.arunkr.saavn.downloader.DownloadService.insert_into_database(DownloadService.java:104)
	at com.arunkr.saavn.downloader.DownloadService.addToDownload(DownloadService.java:99)
	at com.arunkr.saavn.downloader.DownloadService.onHandleIntent(DownloadService.java:66)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by arunKumarNOP** [comment]
Its pretty strange bug and only on MI phones, but not all MI phones.

I was passing Build Version as the Version to the SQLiteOpenHelper which is positive number, very strange. If anyone else knows the reason let me know.

I have made appropriate changes in https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/8096872dfea77e28459418dbb4b8b9e7a3c3cb79 by changing the Database Version to be passed as a constant 1 and project upgraded to Android Studio 2.3.

Check it and let me know if it fixed it.
